# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  # batch = true so not every commit triggers the build
  batch: true 
  branches:
    include:
    - master
  paths:
    # include all paths as trigger for changes
    include:
    - .
pool:
  vmImage: 'Ubuntu-20.04'

variables:
  solution: '**/*.sln'
  buildConfiguration: 'Release'
  runtime: 'win-x64'

stages:
# test, sonar
- template: /build/pipelines/stages/teststage.yaml

- stage: Build
  dependsOn: Test
  displayName: Build and push stage
  jobs:  
    - job: Build
      displayName: Build
      steps:
       - task: PublishBuildArtifacts@1
         inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)\Artifacts'
          ArtifactName: 'BackendAppTest'
          publishLocation: 'Container'