# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  # batch = true so not every commit triggers the build
  batch: 'true'
  branches:
    include:
    - 'master'
    - '59725'
  paths:
    # include all paths as trigger for changes
    include:
    - .


pool:
  #vmImage: 'Ubuntu-20.04'
  name: 'CIBG-BuildRelease-O'

variables:
  solution: '**/*.sln'
  buildConfiguration: 'Release'
  runtime: 'win-x64'  
  ProjectsToTest: "src/**/*.Tests.csproj"

  # Publishing
  Publish.ArtifactName: "drop2"
  Apps.Content.WebApi.ArtifactSubDirectory: "ContentApi"
  Apps.App.IccPortal.ArtifactSubDirectory: "IccPortalApp"
  Apps.Icc.WebApi.ArtifactSubDirectory: "IccWebApi"
  Apps.MobileAppApi.WebApi.ArtifactSubDirectory: "MobileAppApi"
  Apps.DailyCleanup.ArtifactSubDirectory: "DailyCleanup"
  Apps.EksEngine.ArtifactSubDirectory: "EksEngine"
  Apps.IksDownloader.ArtifactSubDirectory: "EfgsDownloader"
  Apps.IksUploader.ArtifactSubDirectory: "EfgsUploader"
  Apps.ManifestEngine.ArtifactSubDirectory: "ManifestEngine"
  Tools.PublishContent.ArtifactSubDirectory: "PublishContent"
  Tools.GenTeks.ArtifactSubDirectory: "GenTeks"
  Tools.ForceTekAuth.ArtifactSubDirectory: "ForceTekAuth"
  Tools.SigTestFileCreator.ArtifactSubDirectory: "SigTestFileCreator"
  Tools.Eks.Parser.ArtifactSubDirectory: "Eks.Parser"
  
stages:
# Tests all unittest in 'ProjectsToTest'
- template: /build/pipelines/stages/test-stage.yaml

# Publish build and push content.webapi stage
- stage: Build
  dependsOn: Test
  displayName: 'Publish builds'
  jobs:  
  #Apps
  - template: /build/pipelines/jobs/apps-publish-contentwebapi-artifact.yaml
  #- template: /build/pipelines/jobs/apps-publish-appiccportal-artifact.yaml
  - template: /build/pipelines/jobs/apps-publish-iccwebapi-artifact.yaml
  - template: /build/pipelines/jobs/apps-publish-mobileappipawebapi-artifact.yaml
  - template: /build/pipelines/jobs/apps-publish-dailycleanup-artifact.yaml
  - template: /build/pipelines/jobs/apps-publish-eksengine-artifact.yaml
  - template: /build/pipelines/jobs/apps-publish-iksdownloader-artifact.yaml
  - template: /build/pipelines/jobs/apps-publish-iksuploader-artifact.yaml
  - template: /build/pipelines/jobs/apps-publish-manifestengine-artifact.yaml
  #Tools
  - template: /build/pipelines/jobs/tools-publish-eksparcer-artifact.yaml
  - template: /build/pipelines/jobs/tools-publish-forcetekauth-artifact.yaml
  - template: /build/pipelines/jobs/tools-publish-genteks-artifact.yaml
  - template: /build/pipelines/jobs/tools-publish-publishcontent-artifact.yaml
  - template: /build/pipelines/jobs/tools-publish-sigtestfilecreator-artifact.yaml
  #Other
  #- template: