# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


pool:
  #vmImage: 'Ubuntu-20.04'
  name: 'CIBG-BuildRelease-O'

variables:
  solution: '**/*.sln'
  buildConfiguration: 'Release'
  runtime: 'win-x64'  
  ProjectsToTest: "src/**/*.Tests.csproj"

  Content.WebApi.ArtifactSubDirectory: "ContentApi"
  App.IccPortal.ArtifactSubDirectory: "IccPortalApp"
  Icc.WebApi.ArtifactSubDirectory: "IccWebApi"
  MobileAppApi.WebApi.ArtifactSubDirectory: "MobileAppApi"

stages:
#- template: /build/pipelines/stages/test-stage.yaml

# Publish build and push content.webapi stage
- stage: Build
  #dependsOn: Test
  displayName: 'Publish builds'
  jobs:  
  #- template: /build/pipelines/stages/publish-contentwebapi-artifact-stage.yaml
  - template: /build/pipelines/stages/publish-appiccportal-artifact-stage.yaml
  - template: /build/pipelines/stages/publish-iccwebapi-artifact-stage.yaml
  #- template: /build/pipelines/stages/publish-mobileappipawebapi-artifact-stage.yaml