version: '3'
services:
  content_api:
    build:
      context: ..
      dockerfile: docker/standalone/Dockerfile
    image: standalone:latest
    entrypoint: ['/bin/sh', '-c', 'cd ContentApi && ./NL.Rijksoverheid.ExposureNotification.BackEnd.ContentApi']
    ports:
      - '5004:5000'
    links:
      - 'db:database'
  mobile_api:
    build:
      context: ..
      dockerfile: docker/standalone/Dockerfile
    image: standalone:latest
    entrypoint: ['/bin/sh', '-c', 'cd MobileAppApi && ./NL.Rijksoverheid.ExposureNotification.BackEnd.MobileAppApi']
    ports:
      - '5005:5000'
    links:
      - 'db:database'
  jobs_api:
    build:
      context: ..
      dockerfile: docker/standalone/Dockerfile
    image: standalone:latest
    entrypoint: ['/bin/sh', '-c', 'cd BatchJobsApi && ./NL.Rijksoverheid.ExposureNotification.BackEnd.BatchJobsApi']
    ports:
      - '5006:5000'
    links:
      - 'db:database'
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "mss-nl-covid-19-dev"
      ACCEPT_EULA: "Y"