version: '3.9'
services:
  tools:
    build:
      context: ..
      dockerfile: docker/development/Dockerfile.DbProvision
    image: standalone-tools:latest
    links:
      - 'db:database'
    depends_on:
      - 'db'
  content_api:
    build:
      context: ..
      dockerfile: docker/development/Dockerfile.Dist
    image: standalone-dist:latest
    entrypoint: ['/bin/sh', '-c', 'cd Content.WebApi && ./NL.Rijksoverheid.ExposureNotification.BackEnd.Content.WebApi']
    ports:
      - '5004:5000'
    links:
      - 'db:database'
    depends_on:
      - 'tools'
  mobile_api:
    build:
      context: ..
      dockerfile: docker/development/Dockerfile.MobileApi
    image: standalone-mobile.api:latest
    entrypoint: ['/bin/sh', '-c', 'cd MobileAppApi.WebApi && ./NL.Rijksoverheid.ExposureNotification.BackEnd.MobileAppApi']
    ports:
      - '5005:5000'
    links:
      - 'db:database'
    depends_on:
      - 'tools'
  icc-backend:
    build:
      context: ..
      dockerfile: docker/development/Dockerfile.IccBackend
    image: standalone-icc.api:latest
    entrypoint: ['/bin/sh', '-c', 'cd Icc.WebApi && ./NL.Rijksoverheid.ExposureNotification.BackEnd.Applications.Icc.WebApi']
    ports:
      - '5006:5000'
    links:
      - 'db:database'
    depends_on:
      - 'tools'
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"    
    environment:
      SA_PASSWORD: "mss-nl-covid-19-dev"
      ACCEPT_EULA: "Y"